"use strict";
// let num1: number = 5;
// console.log(num1);
// let num1: number = 5;
// let num2: number = 8;
// let sum: number = num1 + num2;
// console.log("The sum of num1 and num2 is:", sum);
// let str: string = "Hello, world!";
// console.log(str);
// let str: string = "Hello, world!";
// var length: number = str.length;
// console.log(length);
// let bool: boolean = true;
// console.log(bool);
// let bool: boolean = true;
// let notBool: boolean = !bool;
// console.log(notBool);
// let bool: boolean = true;
// let notBool: boolean = !bool;
// let andResult: boolean = bool && notBool;
// console.log(andResult);
// let bool: boolean = true;
// let notBool: boolean = !bool;
// let orResult: boolean = bool || notBool;
// console.log(orResult);
// let bool: boolean = true;
// let notBool: boolean = !bool;
// let orResult: boolean = bool || notBool;
// console.log(orResult);
// let num1: number = 5;
// let num2: number = 8;
// let num3: number = 2;
// let num4: number = 3;
// let multiplicationResult: number = num4 * num2;
// let additionResult: number = num1 + num3;
// let isEqual: boolean = multiplicationResult === additionResult;
// console.log("Is num4 multiplied by num2 equal to num1 plus num3?", isEqual);
// let num1: number = 10;
// let isEven: boolean = num1 % 2 == 0;
// console.log(isEven);
// let num2: number = -5;
// let isPositive: boolean = num2 > 0;
// console.log(isPositive);
// let str: string = "Hello";
// let isTruthy: boolean = !!str;
// console.log(isTruthy);
